server:
  port: 80
spring:
  application:
    name: api-gateway
  redis:
    host: 192.168.200.128
    port: 6379
    database: 0
    timeout: 1800000
    password:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.128:8848
    gateway:
      discovery: #Whether to be combined with the service discovery component, forwarded to a specific service instance through serviceId (must be set to uppercase). The default is false, set to true to enable the function of automatically creating routes based on serviceId through the service center.
        locator: #Routing access method: http://Gateway_HOST:Gateway_PORT/uppercase serviceId/**, where the microservice application name is accessed by default in uppercase.
          enabled: true
      routes:
        - id: service-product
          uri: lb://service-product
          predicates:
            -Path=/*/product/** # Path matching
        - id: service-item
          uri: lb://service-item
          predicates:
            -Path=/*/item/** # Path matching
        - id: service-user
          uri: lb://service-user
          predicates:
            -Path=/*/user/**
        - id: service-cart
          uri: lb://service-cart
          predicates:
            -Path=/*/cart/**
        - id: service-order
          uri: lb://service-order
          predicates:
            -Path=/*/order/**
        - id: service-payment
          uri: lb://service-payment
          predicates:
            -Path=/*/payment/** # Path matching
        - id: service-activity
          uri: lb://service-activity
          predicates:
            -Path=/*/activity/** # Path matching
        #==================web frontend==========================
        - id: web-item
          uri: lb://web-all
          predicates:
            -Host=item.gmall.com
        #==================Home front end==========================
        - id: web-index
          uri: lb://web-all
          predicates:
            -Host=www.gmall.com
        - id: web-list
          uri: lb://web-all
          predicates:
            -Host=list.gmall.com
        - id: web-passport
          uri: lb://web-all
          predicates:
            -Host=passport.gmall.com
        - id: web-cart
          uri: lb://web-all
          predicates:
            -Host=cart.gmall.com
        - id: web-order
          uri: lb://web-all
          predicates:
            -Host=order.gmall.com
        - id: web-payment
          uri: lb://web-all
          predicates:
            -Host=payment.gmall.com
        - id: web-activity
          uri: lb://web-all
          predicates:
            -Host=activity.gmall.com
authUrls:
  url: trade.html,myOrder.html #,list.html,addCart.html