server:
  port: 8206

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*Mapper.xml # Writing complex sql statements, mybatis-plus has poor support for multi-table association. Handwritten xml file {sql statement}

spring:

  rabbitmq:
    host: 192.168.0.13
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual #By default, the message consumer automatically acknowledges the message, if you want to manually acknowledge the message, you need to modify the confirmation mode to manual
        prefetch: 1 # The number of messages that the consumer gets from the queue each time. When this attribute is not set, it is: polling distribution, and it is set to 1: fair distribution
  redis:
    host: 192.168.0.13
    port: 6379
    database: 0
    timeout: 1800000
    password:
    lettuce:
      pool:
        max-active: 20 #Maximum number of connections
        max-wait: -1 #Maximum blocking waiting time (negative number means no limit)
        max-idle: 5 #Maximum idle
        min-idle: 0 #Minimum idle
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/gmall
    username: root
    password: 1234
    hikari:
      connection-test-query: SELECT 1 # Automatically detect connection
      connection-timeout: 60000 #Database connection timeout time, the default is 30 seconds
      idle-timeout: 500000 #The maximum survival time of idle connections, the default is 600000 (10 minutes)
      max-lifetime: 540000 #This attribute controls the longest life cycle of the connection in the pool, a value of 0 means an infinite life cycle, and the default is 1800000, which is 30 minutes
      maximum-pool-size: 12 #The maximum number of connections in the connection pool, the default is 10
      minimum-idle: 10 #Minimum number of idle connections
      pool-name: SPHHikariPool # Connection pool name
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
fileServer:
  url: http://127.0.0.1:8080/ # fastDFS distributed file system ip:port